version: "3.7"
services:
  nginx:
    image: "kuji-nginx"
    build:
      context: ../
      dockerfile: ./docker_build/nginx/Dockerfile
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - app
    restart: always
    networks:
      - kuji
    volumes:
      - shared-volume:/app/bedrock
  app:
    image: kuji-app
    build:
      context: ../
      dockerfile: ./docker_build/app/Dockerfile
    restart: always
    networks:
      - kuji
      - mysql
    volumes:
      - shared-volume:/app/bedrock
networks:
  mysql:
    external: true
    name: mysql_default
  kuji:

## Local Development
# volumes:
#   shared-volume:
#     driver_opts:
#       type: none
#       device: /abs/path/to/bedrock/dir
#       o: bind

## Building Image for Deploy
volumes:
  shared-volume:
